//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:21:46 PM CST 
//


package xyz.liuzm.accumulation.developer_platform.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}web_ui"/&gt;
 *         &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}data_nodes"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "developer_platform")
public class DeveloperPlatform {

    @XmlElement(name = "web_ui", required = true)
    protected WebUi webUi;
    @XmlElement(name = "data_nodes", required = true)
    protected DataNodes dataNodes;

    /**
     * Gets the value of the webUi property.
     * 
     * @return
     *     possible object is
     *     {@link WebUi }
     *     
     */
    public WebUi getWebUi() {
        return webUi;
    }

    /**
     * Sets the value of the webUi property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebUi }
     *     
     */
    public void setWebUi(WebUi value) {
        this.webUi = value;
    }

    /**
     * Gets the value of the dataNodes property.
     * 
     * @return
     *     possible object is
     *     {@link DataNodes }
     *     
     */
    public DataNodes getDataNodes() {
        return dataNodes;
    }

    /**
     * Sets the value of the dataNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataNodes }
     *     
     */
    public void setDataNodes(DataNodes value) {
        this.dataNodes = value;
    }

}
