//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:21:46 PM CST 
//


package xyz.liuzm.accumulation.developer_platform.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.biocloud.app.developer_platform.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Label_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "label");
    private final static QName _Description_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "description");
    private final static QName _Value_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "value");
    private final static QName _Dependency_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "dependency");
    private final static QName _SelectNameOne_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "select_name_one");
    private final static QName _SelectNameTwo_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "select_name_two");
    private final static QName _ValidationRules_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "validation_rules");
    private final static QName _Source_QNAME = new QName("http://www.bioCloud.net/developer_platform.xsd", "source");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.biocloud.app.developer_platform.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeveloperPlatform }
     * 
     */
    public DeveloperPlatform createDeveloperPlatform() {
        return new DeveloperPlatform();
    }

    /**
     * Create an instance of {@link WebUi }
     * 
     */
    public WebUi createWebUi() {
        return new WebUi();
    }

    /**
     * Create an instance of {@link RawData }
     * 
     */
    public RawData createRawData() {
        return new RawData();
    }

    /**
     * Create an instance of {@link Radios }
     * 
     */
    public Radios createRadios() {
        return new Radios();
    }

    /**
     * Create an instance of {@link Radio }
     * 
     */
    public Radio createRadio() {
        return new Radio();
    }

    /**
     * Create an instance of {@link Select }
     * 
     */
    public Select createSelect() {
        return new Select();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link DifferenceGrouping }
     * 
     */
    public DifferenceGrouping createDifferenceGrouping() {
        return new DifferenceGrouping();
    }

    /**
     * Create an instance of {@link DataNodes }
     * 
     */
    public DataNodes createDataNodes() {
        return new DataNodes();
    }

    /**
     * Create an instance of {@link DataNode }
     * 
     */
    public DataNode createDataNode() {
        return new DataNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "dependency")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDependency(String value) {
        return new JAXBElement<String>(_Dependency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "select_name_one")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSelectNameOne(String value) {
        return new JAXBElement<String>(_SelectNameOne_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "select_name_two")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSelectNameTwo(String value) {
        return new JAXBElement<String>(_SelectNameTwo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "validation_rules")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createValidationRules(String value) {
        return new JAXBElement<String>(_ValidationRules_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.bioCloud.net/developer_platform.xsd", name = "source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSource(String value) {
        return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
    }

}
