//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:21:46 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bioCloud.net/developer_platform.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xyz.liuzm.accumulation.developer_platform.xml;
