//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.01.18 at 05:21:46 PM CST 
//


package xyz.liuzm.accumulation.developer_platform.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}raw_data"/&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}radios"/&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}select"/&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}group"/&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}input"/&gt;
 *           &lt;element ref="{http://www.bioCloud.net/developer_platform.xsd}difference_grouping"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rawDataOrRadiosOrSelect"
})
@XmlRootElement(name = "web_ui")
public class WebUi {

    @XmlElements({
        @XmlElement(name = "raw_data", type = RawData.class),
        @XmlElement(name = "radios", type = Radios.class),
        @XmlElement(name = "select", type = Select.class),
        @XmlElement(name = "group", type = Group.class),
        @XmlElement(name = "input", type = Input.class),
        @XmlElement(name = "difference_grouping", type = DifferenceGrouping.class)
    })
    protected List<Object> rawDataOrRadiosOrSelect;

    /**
     * Gets the value of the rawDataOrRadiosOrSelect property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rawDataOrRadiosOrSelect property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRawDataOrRadiosOrSelect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RawData }
     * {@link Radios }
     * {@link Select }
     * {@link Group }
     * {@link Input }
     * {@link DifferenceGrouping }
     * 
     * 
     */
    public List<Object> getRawDataOrRadiosOrSelect() {
        if (rawDataOrRadiosOrSelect == null) {
            rawDataOrRadiosOrSelect = new ArrayList<Object>();
        }
        return this.rawDataOrRadiosOrSelect;
    }

}
